spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/beershop
    username: sa
    password:
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081